const COLLECTIONS = {
  COMPANIES: "leadflow_companies",
  LEADS: "leadflow_leads",
  EVENTS: "leadflow_lead_events",
  HANDOFFS: "leadflow_handoffs",
  // Solo Cloud Functions (Admin SDK) — firestore.rules las deniega al
  // navegador vía la regla catch-all.
  EMAIL_QUOTA: "leadflow_email_quota",
  TRIAL_SIGNUPS: "leadflow_trial_signups",
};

const LEAD_STATUS = {
  NEW: "NEW",
  ANALYZING: "ANALYZING",
  QUALIFIED: "QUALIFIED",
  CONTACTED: "CONTACTED",
  BOOKING_SENT: "BOOKING_SENT",
  APPOINTMENT_BOOKED: "APPOINTMENT_BOOKED",
  HUMAN_REVIEW: "HUMAN_REVIEW",
  NURTURE: "NURTURE",
  CLOSED: "CLOSED",
};

const HANDOFF_TRIGGER = {
  AI_LOW_CONFIDENCE: "AI_LOW_CONFIDENCE",
  SENSITIVE_TOPIC: "SENSITIVE_TOPIC",
  PRICE_NEGOTIATION: "PRICE_NEGOTIATION",
  CUSTOMER_REQUEST: "CUSTOMER_REQUEST",
  BUSINESS_RULE: "BUSINESS_RULE",
};

const EVENT_TYPE = {
  STATUS_CHANGE: "STATUS_CHANGE",
  AI_ANALYSIS: "AI_ANALYSIS",
  AI_REPLY_GENERATED: "AI_REPLY_GENERATED",
  FOLLOW_UP_SENT: "FOLLOW_UP_SENT",
  HANDOFF_CREATED: "HANDOFF_CREATED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  MANUAL_EDIT: "MANUAL_EDIT",
};

module.exports = { COLLECTIONS, LEAD_STATUS, HANDOFF_TRIGGER, EVENT_TYPE };
